### ISSUE TITLE
fixing video html display 

### ISSUE THREAD

**Issue by orm011** [mkornacker/pixeltable#39]
Proposed change so we can reliably see videos:
1. have a basic webserver running with a fixed pixeltable root (can start with python -m http.server --directory=$PIXELTABLE_HOME). This is inited started during env setup and some available port found. This is useful for multiple things.

2. Given a video column, if the video is local to pixeltable home, all set. If not, then before visualizing, create symlink to original video path within PIXELTABLE_HOME.
4. in html rep now a source url to that server, the symlink path relative to the (fixed and known) root will always work.
5. As an aside, functions with video output like make_video() should save videos to some folder in pixetable_home rather than current dir. 
6. Tested basics of approach on external video on jupyter, works.

**Comment by orm011** [comment]
As a bonus, this type of thing also works with audio, and images (which make notebooks large when embedded).

**Comment by mkornacker** [comment]
Sounds like a good idea. Let's discuss the specifics offline.

**Comment by orm011** [comment]
fixed. 2d2bc97aad1d7
