### ISSUE TITLE
make pixeltable pip installable

### ISSUE THREAD

**Issue by orm011** [mkornacker/pixeltable#45]
We would like to make pixeltable easy to try out by any potential user.
Eg. research users. 
This would be helpful both for adoption but also to get feedback quicker.

Making pixeltable pip installable and removing docker dependency
is the main way to make it easy to try out without requiring admin access (eg to install docker, or otherwise have postgres)

The main issues are to deal with the (dependency, platform)  matrix below:
* macos+apple silicon is a good target for people to test it out or to eg. develop against it.

<table border="1">
<tr>
 <td></td>
<td>many linux + amd64 </td>
<td>macos+apple silicon</td>
</tr>
  <tr>
    <td>postgres server</td>
    <td> todo</td>
    <td> todo </td>
  </tr>
  <tr>
    <td>pg vector ext</td>
    <td> todo </td>
    <td> todo </td>
  </tr>
  <tr>
   <td> nos </td>
    <td>todo</td>
    <td>todo</td>
  </tr>
</table>

An alternative is to use conda to manage some of these dependencies, as there are postgres and pgvector packages available.

Resources:
https://github.com/michelp/postgresql-wheel/ shows how to make postgres available.
Lacks macos or pgvector support , but shows you can easily add postgis, for example.

**Comment by mkornacker** [comment]
commit fd31eede3ba57615b6e47e9a4fb709ff57a66157
Author: Oscar Moll <orm@csail.mit.edu>
Date:   Tue Jan 9 14:13:41 2024 -0500

    Switch to using pgserver for postgres
