### ISSUE TITLE
Pixeltable throws error while reading the corrupt videos and stops the process

### ISSUE THREAD

**Issue by mohsin-ashraf** [mkornacker/pixeltable#50]
**Description**
Hi team, we are using Pixeltable for some video processing-related tasks. We have hundreds of thousands of videos that we process. In all those videos, some videos can be corrupt and cannot be loaded, so Pixeltable is loading and reading the video frames and when it encounters the corrupt videos it throws the following error and stops processing the further videos.

```
023-12-04 15:38:35,407 INFO env env.py:209: connecting to NOS
2023-12-04 15:38:35.466 | INFO     | nos.server:init:131 - Inference server already running (name=nos-inference-service-cpu, image=<Image: 'autonomi/nos:0.0.9-cpu'>, id=ed0f340b6148).
2023-12-04 15:38:35,467 INFO env env.py:212: waiting for NOS
2023-12-04 15:38:35,527 INFO env env.py:176: found database postgresql://postgres:*****@localhost:6543/pixeltable
Backend MacOSX is interactive backend. Turning interactive mode on.
Inserting rows into table: 4740rows [00:02, 1730.77rows/s]
OpenCV: Couldn't read video stream from file "/Users/mohsinashraf/.pixeltable/filecache/2887262927fa4e1192ff19492b39a3de_1_595e390ff2e8900a318675d1591a0ae0e99b54cba7cc86693364614c32025284"
[ERROR:0@1275.009] global cap.cpp:166 open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.8.1) /Users/xperience/GHA-OpenCV-Python/_work/opencv-python/opencv-python/opencv/modules/videoio/src/cap_images.cpp:267: error: (-215:Assertion failed) number < max_number in function 'icvExtractPattern'	
```
The above error occurred due to the following video.

https://github.com/mkornacker/pixeltable/assets/18676812/67165c17-d2be-434a-8307-0d2493d38ef8

**Ask**
The ask is we have thousands of videos to process, and we want the Pixeltable to ignore the videos which are erroneous and move on to process other videos.
It could leave a None value for the failing videos.

**Comment by mkornacker** [comment]
commit 43b6f43773d8549b432167ae024157952d8be4d3
Author: Oscar Moll <orm@csail.mit.edu>
Date:   Thu Dec 21 21:38:55 2023 -0500

    Issue 50: handling media validation errors during insert
    
    - similar to computed column exceptions, media validation errors can now also
      be recorded as errors within the table (with properties errortype/-msg)
    - this is controlled by kw parameter fail_on_exception of
      InsertableTable.insert()
