### ISSUE TITLE
Selecting the video frames at less then 1 FPS.

### ISSUE THREAD

**Issue by mohsin-ashraf** [mkornacker/pixeltable#58]
Hi team, I am looking to extract frames of the videos at less than 1 FPS, e.g., I have a video of 10 seconds, and I want to extract 1 frame every other second or 1 frame every 2 seconds.
I am wondering if the Pixeltable supports this.

**Comment by mkornacker** [comment]
commit 86c03a45073bfe90a98ebfc9acbfb1a317abbe6b
Author: Marcel Kornacker <marcelk@gmail.com>
Date:   Tue Jan 9 11:15:07 2024 -0800

    Issue 58: video frame iteration at fps < 1.0
